apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainingRuntime
metadata:
  name: single-gpu-runtime
  labels:
    trainer.kubeflow.org/framework: torch
spec:
  mlPolicy:
    numNodes: 1
    torch:
      numProcPerNode: 1
  template:
    spec:
      replicatedJobs:
        - name: node
          groupName: default
          replicas: 1
          template:
            metadata:
              labels:
                learning.kubeflow.org/runtime: single-gpu-runtime
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  runtimeClassName: nvidia
                  containers:
                    - name: node
                      image: python:3.11-slim
                      resources: {}
